/*
    DO NOT EDIT THIS FILE DIRECTLY
    This file was generated by a script in FMOD Studio 
*/

package;

class FmodSongs {
    public static inline var LetsGo:String = "event:/Music/LetsGo";
    public static inline var Maybe:String = "event:/Music/Maybe";
}

class FmodSFX {
    public static inline var squeak:String = "event:/SFX/BabyMole/squeak";
    public static inline var MenuHover:String = "event:/SFX/Menu/MenuHover";
    public static inline var MenuSelect:String = "event:/SFX/Menu/MenuSelect";
    public static inline var Dig:String = "event:/SFX/Mole/Dig";
    public static inline var Dig1:String = "event:/SFX/Mole/Dig/Dig1";
    public static inline var Dig2:String = "event:/SFX/Mole/Dig/Dig2";
    public static inline var Dig3:String = "event:/SFX/Mole/Dig/Dig3";
}
