/*
    DO NOT EDIT THIS FILE DIRECTLY
    This file was generated by a script in FMOD Studio 
*/

package;

class FmodSongs {
    public static inline var LetsGo:String = "event:/Music/LetsGo";
    public static inline var Maybe:String = "event:/Music/Maybe";
}

class FmodSFX {
    public static inline var BabyMoleCollect:String = "event:/SFX/BabyMole/BabyMoleCollect";
    public static inline var BabyMoleSqueak:String = "event:/SFX/BabyMole/BabyMoleSqueak";
    public static inline var MenuHover:String = "event:/SFX/Menu/MenuHover";
    public static inline var MenuSelect:String = "event:/SFX/Menu/MenuSelect";
    public static inline var Dig1:String = "event:/SFX/Mole/Dig/Dig1";
    public static inline var Dig2:String = "event:/SFX/Mole/Dig/Dig2";
    public static inline var Dig3:String = "event:/SFX/Mole/Dig/Dig3";
    public static inline var MoleDig:String = "event:/SFX/Mole/MoleDig";
    public static inline var MoleFall:String = "event:/SFX/Mole/MoleFall";
    public static inline var MoleFallLand:String = "event:/SFX/Mole/MoleFallLand";
    public static inline var MoleRock:String = "event:/SFX/Mole/MoleRock";
    public static inline var SnakeEatMole:String = "event:/SFX/Snake/SnakeEatMole";
}
